### ISSUE TITLE
"Development has been suspended indefinitely"?

### ISSUE THREAD

**Issue by Oberon00** [cloudfoundry/istio-release#13]
In the README of this repository, there is this sentence:

> Note: This release is beta and not ready for use. Development on this release has been suspended indefinitely.

What is meant by "this release"? Has development been suspended on this repository (seems not so, looking at the commits)? Or on some particular version (then this should not be in the develop branch, first thing I see when opening this repo on GitHub)?

**Comment by rosenhouse** [comment]
This project is stopped.  I've updated the README to be more clear.  If you're looking for Istio integration with Cloud Foundry, please check out https://github.com/cloudfoundry/cf-for-k8s
