### ISSUE TITLE
Pilot built without version information

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/istio-release#3]
The gobuild script istio uses captures build information

Here's the invocation
https://github.com/istio/istio/blob/99d9f3fda4bd7ae1a851306a0140d67ca3c324cd/bin/gobuild.sh#L56

The script sets these properties when building the go application
https://github.com/istio/istio/blob/99d9f3fda4bd7ae1a851306a0140d67ca3c324cd/bin/get_workspace_status.sh#L49

This is exposed when running the `version` command for the binary

I don't see these settings set in pilot's packaging's script

https://github.com/cloudfoundry/istio-release/blob/3abd67fc90f783c507360e0f69df60da4367e6c1/packages/pilot/packaging#L10

**Comment by zachgersh** [comment]
So I was thinking about this @dprotaso and wanted to know what most people do for external dependencies they are building themselves. Do we just make it a SHA of the repo we used? Do we try to mirror some version number? Do we make up our own (hate this idea but good to document that we shouldn't do it).

Feels like SHA is the best idea but I am sure we are open to other suggestions.

**Comment by dprotaso** [comment]
I’d prefer SHA but do as you please

**Comment by utako** [comment]
@dprotaso Are you asking for Pilot provided in istio-release to have versioning info to help with debugging and development? Are there any other user benefits that would help @shubhaat and @shalako prioritize this in our backlog?

Thanks,
@utako, CF Routing Team

**Comment by dprotaso** [comment]
I have no preference - feel free to close this if you think it isn’t
beneficial to you .

**Comment by rosenhouse** [comment]
Istio integration with CF is now happening in https://github.com/cloudfoundry/cf-for-k8s via https://github.com/cloudfoundry/cf-k8s-networking
