### ISSUE TITLE
Generate valid serviceNode strings

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/istio-release#7]
Pilot expects the [Envoy `serviceNode` field](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto#envoy-api-field-core-node-id) to have a certain format, e.g.
```
role~ip~id~dns.domain
```
We can see the [implementation here](https://github.com/istio/istio/blob/b8e30e07ec7b36cf1ba1b445b78c81fdf0d417b9/pilot/pkg/model/context.go#L230-L270).

For the istio ingress router, we're [currently just generating](https://github.com/cloudfoundry/istio-release/blob/75901216770f7fe473269e8018649eec3a378cd0/jobs/envoy/templates/bpm.yml.erb#L9)
```
router~x~x~x
```

That this works at all is kind of surprising, since it is relying on undocumented behavior.  In particular, the node IDs really ought to be unique.

Let's fix this for the ingress router.  While we're at it, we could remove [this config from the command-line](https://github.com/cloudfoundry/istio-release/blob/75901216770f7fe473269e8018649eec3a378cd0/jobs/envoy/templates/bpm.yml.erb#L9) and instead just [use what we've got in the bootstrap config file](https://github.com/cloudfoundry/istio-release/blob/75901216770f7fe473269e8018649eec3a378cd0/jobs/envoy/templates/envoy.json.erb#L10).

potential follow-up: change Diego [executor code for setting the same property on the sidecars](https://github.com/cloudfoundry/executor/blob/aab5d4263aaa42c374e974a25e96a30d1cfc5fa5/depot/transformer/transformer.go#L725-L726).

**Comment by rosenhouse** [comment]
Fix for sidecars in Diego: https://github.com/cloudfoundry/executor/pull/42

**Comment by rosenhouse** [comment]
I have a branch for this here: https://github.com/cloudfoundry/istio-release/compare/routers-have-unique-ids

**Comment by christianang** [comment]
LGTM. Merged branch.
