### ISSUE TITLE
CF handles mTLS between applications, so app devs don't have to

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/istio-release#8]
Adding support for mTLS between applications adds cost and complexity to every application. If the Envoy sidecars in Cloud Foundry handled mTLS between them for direct application-to-application communications, this would eliminate this cost.

This issue is a place for the OSS community to track the CF Networking team's progress, and contribute use cases.

If anyone in the community would like to help with the implementation, please let us know!

**Comment by rosenhouse** [comment]
Istio integration with CF is now happening in https://github.com/cloudfoundry/cf-for-k8s via https://github.com/cloudfoundry/cf-k8s-networking
